site_name: <%= project.name %>
nav:
    - Intro: index.md
    - Plan: plan.md
    - Define: define.md
    - Design: design.md
theme:
    name: "material"
markdown_extensions:
    - admonition
    - pymdownx.keys
    - pymdownx.emoji
    - pymdownx.tabbed
    - pymdownx.details
    - pymdownx.snippets
    - pymdownx.tasklist
    - pymdownx.arithmatex
    - pymdownx.inlinehilite
    - pymdownx.highlight:
          linenums: true
    - pymdownx.superfences:
          custom_fences:
              - name: mermaid
                class: mermaid
                format: !!python/name:pymdownx.superfences.fence_div_format
extra_javascript:
    - https://unpkg.com/mermaid@8.6.4/dist/mermaid.min.js
    - https://polyfill.io/v3/polyfill.min.js?features=es6
    - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
